"""initial schema

Revision ID: 9680849ca6fb
Revises: 
Create Date: 2026-07-16 14:34:23.737916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9680849ca6fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causal_chains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_value', sa.String(length=200), nullable=False),
    sa.Column('hop1_type', sa.String(length=30), nullable=True),
    sa.Column('hop1_target', sa.String(length=100), nullable=True),
    sa.Column('hop1_relationship', sa.String(length=50), nullable=True),
    sa.Column('hop2_type', sa.String(length=30), nullable=True),
    sa.Column('hop2_target', sa.String(length=100), nullable=True),
    sa.Column('hop2_relationship', sa.String(length=50), nullable=True),
    sa.Column('hop3_type', sa.String(length=30), nullable=True),
    sa.Column('hop3_target', sa.String(length=100), nullable=True),
    sa.Column('hop3_relationship', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classified_news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('commodity', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('impact_type', sa.String(length=30), nullable=True),
    sa.Column('impact_direction', sa.String(length=20), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classified_news_commodity'), 'classified_news', ['commodity'], unique=False)
    op.create_index('ix_classified_news_commodity_impact', 'classified_news', ['commodity', 'impact_direction'], unique=False)
    op.create_index('ix_classified_news_published', 'classified_news', ['published_at'], unique=False)
    op.create_index(op.f('ix_classified_news_sector'), 'classified_news', ['sector'], unique=False)
    op.create_table('commodity_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commodity_prices_source', 'commodity_prices', ['source'], unique=False)
    op.create_index(op.f('ix_commodity_prices_symbol'), 'commodity_prices', ['symbol'], unique=False)
    op.create_index('ix_commodity_prices_symbol_timestamp', 'commodity_prices', ['symbol', 'timestamp'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=500), nullable=True),
    sa.Column('ticker_nse', sa.String(length=20), nullable=True),
    sa.Column('ticker_bse', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('website_domain', sa.String(length=255), nullable=True),
    sa.Column('ir_page_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('market_cap_inr', sa.Integer(), nullable=True),
    sa.Column('listing_status', sa.String(length=20), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('delisting_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('geopolitical_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('goldstein_scale', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_geopolitical_events_category', 'geopolitical_events', ['category'], unique=False)
    op.create_index(op.f('ix_geopolitical_events_country'), 'geopolitical_events', ['country'], unique=False)
    op.create_index('ix_geopolitical_events_date_country', 'geopolitical_events', ['event_date', 'country'], unique=False)
    op.create_index(op.f('ix_geopolitical_events_event_id'), 'geopolitical_events', ['event_id'], unique=False)
    op.create_table('sector_exposures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('commodity', sa.String(length=50), nullable=False),
    sa.Column('dependency_type', sa.String(length=30), nullable=False),
    sa.Column('impact_direction', sa.String(length=20), nullable=False),
    sa.Column('impact_magnitude', sa.String(length=20), nullable=False),
    sa.Column('affected_companies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_exposures_sector'), 'sector_exposures', ['sector'], unique=False)
    op.create_index('ix_sector_exposures_sector_commodity', 'sector_exposures', ['sector', 'commodity'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pan_card_number', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('expertise_level', sa.String(length=20), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('investment_horizon', sa.String(length=20), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=False),
    sa.Column('kyc_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('simulation_balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('condition_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('context_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_comparison_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_comparison_snapshots_company', 'company_comparison_snapshots', ['company_id'], unique=False)
    op.create_index('ix_company_comparison_snapshots_expires', 'company_comparison_snapshots', ['expires_at'], unique=False)
    op.create_table('company_themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('theme_name', sa.String(length=100), nullable=False),
    sa.Column('exposure_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('impact_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('validated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compare_flow_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_a_id', sa.UUID(), nullable=False),
    sa.Column('company_b_id', sa.UUID(), nullable=False),
    sa.Column('flow_payload', sa.JSON(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_a_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_b_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_compare_flow_logs_user_created', 'compare_flow_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('etl_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=True),
    sa.Column('filing_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_uri', sa.Text(), nullable=True),
    sa.Column('parsed_text_uri', sa.Text(), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_hash')
    )
    op.create_table('financial_ratios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roce', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ebitda_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ebit_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('interest_coverage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_to_sales', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pat_growth_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eps_growth_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('market_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('impact_level', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_event_type', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_signals_company', 'market_signals', ['company_id'], unique=False)
    op.create_index('ix_market_signals_detected', 'market_signals', ['detected_at'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('relevance_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('affected_dimension', sa.String(length=50), nullable=True),
    sa.Column('tickers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.Column('broker_account_id', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_screens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulated_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_trade', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('pnl_at_close', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulated_trades_user_status', 'simulated_trades', ['user_id', 'status'], unique=False)
    op.create_table('simulator_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('badges', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('daily_challenge_last', sa.String(length=50), nullable=True),
    sa.Column('daily_challenge_done', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('causal_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('trigger_event', sa.String(length=500), nullable=False),
    sa.Column('commodity', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('impact_type', sa.String(length=50), nullable=False),
    sa.Column('impact_direction', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_causal_insights_company_generated', 'causal_insights', ['company_id', 'generated_at'], unique=False)
    op.create_index('ix_causal_insights_portfolio_generated', 'causal_insights', ['portfolio_id', 'generated_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    op.create_index('ix_document_chunks_company_filing', 'document_chunks', ['company_id', 'filing_id'], unique=False)
    op.create_index('ix_document_chunks_filing_date', 'document_chunks', ['filing_date'], unique=False)
    op.create_index('ix_document_chunks_section', 'document_chunks', ['section'], unique=False)
    op.create_table('financial_statements_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_filing_id', sa.UUID(), nullable=True),
    sa.Column('statement_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('is_audited', sa.Boolean(), nullable=False),
    sa.Column('is_consolidated', sa.Boolean(), nullable=False),
    sa.Column('line_item', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('raw_uri', sa.Text(), nullable=False),
    sa.Column('parsed_text_uri', sa.Text(), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vector_namespace', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_companies')
    op.drop_table('user_uploads')
    op.drop_table('holdings')
    op.drop_table('financial_statements_raw')
    op.drop_index('ix_document_chunks_section', table_name='document_chunks')
    op.drop_index('ix_document_chunks_filing_date', table_name='document_chunks')
    op.drop_index('ix_document_chunks_company_filing', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('chat_messages')
    op.drop_index('ix_causal_insights_portfolio_generated', table_name='causal_insights')
    op.drop_index('ix_causal_insights_company_generated', table_name='causal_insights')
    op.drop_table('causal_insights')
    op.drop_table('watchlists')
    op.drop_table('user_transactions')
    op.drop_table('simulator_stats')
    op.drop_index('ix_simulated_trades_user_status', table_name='simulated_trades')
    op.drop_table('simulated_trades')
    op.drop_table('securities')
    op.drop_table('saved_screens')
    op.drop_table('portfolios')
    op.drop_table('news_articles')
    op.drop_index('ix_market_signals_detected', table_name='market_signals')
    op.drop_index('ix_market_signals_company', table_name='market_signals')
    op.drop_table('market_signals')
    op.drop_table('indices')
    op.drop_table('financial_ratios')
    op.drop_table('filings')
    op.drop_table('etl_runs')
    op.drop_index('ix_compare_flow_logs_user_created', table_name='compare_flow_logs')
    op.drop_table('compare_flow_logs')
    op.drop_table('company_themes')
    op.drop_index('ix_company_comparison_snapshots_expires', table_name='company_comparison_snapshots')
    op.drop_index('ix_company_comparison_snapshots_company', table_name='company_comparison_snapshots')
    op.drop_table('company_comparison_snapshots')
    op.drop_table('chat_sessions')
    op.drop_table('alert_rules')
    op.drop_table('users')
    op.drop_index('ix_sector_exposures_sector_commodity', table_name='sector_exposures')
    op.drop_index(op.f('ix_sector_exposures_sector'), table_name='sector_exposures')
    op.drop_table('sector_exposures')
    op.drop_index(op.f('ix_geopolitical_events_event_id'), table_name='geopolitical_events')
    op.drop_index('ix_geopolitical_events_date_country', table_name='geopolitical_events')
    op.drop_index(op.f('ix_geopolitical_events_country'), table_name='geopolitical_events')
    op.drop_index('ix_geopolitical_events_category', table_name='geopolitical_events')
    op.drop_table('geopolitical_events')
    op.drop_table('exchanges')
    op.drop_table('companies')
    op.drop_index('ix_commodity_prices_symbol_timestamp', table_name='commodity_prices')
    op.drop_index(op.f('ix_commodity_prices_symbol'), table_name='commodity_prices')
    op.drop_index('ix_commodity_prices_source', table_name='commodity_prices')
    op.drop_table('commodity_prices')
    op.drop_index(op.f('ix_classified_news_sector'), table_name='classified_news')
    op.drop_index('ix_classified_news_published', table_name='classified_news')
    op.drop_index('ix_classified_news_commodity_impact', table_name='classified_news')
    op.drop_index(op.f('ix_classified_news_commodity'), table_name='classified_news')
    op.drop_table('classified_news')
    op.drop_table('causal_chains')
    # ### end Alembic commands ###
